### ISSUE TITLE
实现猜测

### ISSUE THREAD

**Issue by shuiRong** [fslongjin/This-repo-has-81-stars#1]
我猜是某台服务器上跑着一个程序，一直监听仓库的star数量吧，如果Github没有提供监听事件的话，就是每秒轮询这样子。

数量变化后，调用Github修改仓库标题、详情的接口。

猜测的对吗

**Comment by fslongjin** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    是的，是通过定时请求GitHub的api来实现的。
        
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                fslongjin
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2022年7月14日 ***@***.***> 写道： 




我猜是某台服务器上跑着一个程序，一直监听仓库的star数量吧，如果Github没有提供监听事件的话，就是每秒轮询这样子。

数量变化后，调用Github修改仓库标题、详情的接口。

猜测的对吗



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by WangNianyi2001** [comment]
轮询可太绝了哈哈哈哈哈，我本来以为是 Github Actions😂

**Comment by monsterxcn** [comment]
> > 轮询可太绝了哈哈哈哈哈，我本来以为是 Github Actionsjoy
> 
> 没办法，Actions没有提供Star事件的触发器哈哈哈

有的鸭，这个 [events-that-trigger-workflows#watch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#watch) 不就是吗？

```
on:
  watch:
    types: [started]
```

以前还没有 `workflow_dispatch` 触发的时候，看大家都是用 star + 判断的方式让工作流只有自己 star 才触发。把这个 if 去掉是不就可以了？

```
name: Test

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@v2
# ...
```
